language: node_js
node_js:
- 9.8.0
env:
  global:
  # BB_SITE_ID
  - secure: deAQob8Ag1fol4p3JEeYQ3xTxiiRm5LE/BXwwPSEHXY0yLnNtiKCbtCSeHElMElgSNiWtwBb2zBWwP7ibI5W8QTodQ266kOhwI6GliOp9DEbSDh4prqPrz/7YqdGxokeii3zYKZpdPpKG8qjCZysxeuS+wLYDARN2dxW+5wcMcfEyLMsIwwcoK9hrG6Opsk6DbXPWbqcUTlgt2RxjdzeqFmgyiTLothZIlLWeq3ryURIqrRKzrrSEPNJBLmqESdieRRlL/BgqXWfzW4qqLZ2Uq8hvzxVB/rCsFWXYsXBbhxT3cPT3OHtz+ZmG9WF9BnrAl7KzqOdGM/H/LYOuzUI9I9+2av6DZQ91nhWevfc+3gBFpVv/RwlpEyFPk/jmok7VVPAW6Hgf9hXSPRTqsN7kwLVQEG845yDMjSasxOyvRtxWcWgRQI1Bfc9pbsjVJBdFSuPiKfs2ousXc+3VI+3FjAyX/9QhN2DatcWszWwrSgpN7b6qHZbDB7Bl/shy226YZosL9QTkCiQR48Zebls4MkteIGCyuu8DftQMhvWcu6Gh3owr0G2h7Nh4Wr09P5nxi+SMJrBUxHjioqcz/4H2DK6ioOparYSk4xudCG2+Bd9xRe+Zd1z83+UsCD0X10lBUnccTCPRFXffWiyjD6Z1KqDcWsfu2SqKWHq0nmhor8=

  # BB_CLIENT_ID
  - secure: jT0M2w8GkhPFF1uIEpu9LJj+eZeG+qdfDMzSlxrWuSXb65gzdY+z/leW+RQQnVU/y1dLb8MNk3AdaPgn7WFIbuZnjJ2aXMFeI3Un0D0hFvZKSrIG6KbdWnnSLCz8dNPsY5ZrW9RIuAb2CL6jyNYsJwN2s/Z0k5SBQpSd8H88JbTMmn7byUxqw+HRlUiT1O0NC3tj3KmjGrm3zDRBGCDWGz/Y1y9U4QFaCxPRojEOh7cn1YyD9ZrRckRnsUtvd6F6IDM2QvouNFdFjPVHClVPDkk0kz7rCBKlhD5IAfSoaEyb5NEjMoDPevGDpaQntAVlJ9H+CENbGdH6ZrvdHhz1t6x0324+34U4OHi1GBDU6nEiXoEcCoL9OZCik7v1NA8eRqcPi7ufB3J1UgLuqKo9iGv7Tu7/+Q7oTfzjqM4aTUBTwyebdHVRcFwAK7HbdndczdbKDjU3+sdL/HYf3KLvw6qMPYQMGamhDif3pviH5vVzFYeP8WL2W3rV0wgQXnDYXiM9owD4z1ZpFBwVM6WYvWUqOtK41u3G+I8Gq3VTDLMhc88TioFun3JNTy/hL0rkZ/CknHWFhMO9/liJ2OIEU787RV2rPfO9GqY11N9OLH+LmezrO8ydhTjF4vqpW66Q38/l3tNMnAv8qn78+XILZYLNI9n4CY8J3U3OMBY9Vg4=

  # BB_CLIENT_SECRET
  - secure: Yv4PzvCcH+iwbMjJuXxDD4q2KPvlA0SkNExfeUXwXsoBfE50DdhkDlU7zj+dDUTImVfnG0FWtVSnY1vn91RcRtHD4tgOWyKC7uDan0hhTHsbtZskUZqklyRthEvMx+N53uMqMCUhTzhPY5slKcUoLVhpO00UIOKwy8FJTvX1uELtFL77hwkiGZNWQvYDdFPycSuZEbwieWyedAahvNgXMdexAjKmfKNIJRCdXoVKmMP0ye7VWzbYgyzeFhvlW/0XDdZZhm3JNGFbYX+4xfy9NJqkNdrxuJdmkSkCgyd3wfGhqjWZWSBfA1YSEjFy1Idtjt8C42CN/BZAv+Xn4Jwgzrj8PIUc2QfdGMxZ0GuXF5fw7EoAym8mnfWcEhezeBRA06au+2KYoaeYTBRfIL2tb7KEgxvXu7pAHP+2sBopiIMRk7yJ1LRfx368k+AIm2IGXEgqrXppOD4HsSstJe/GDx1CQCwhqBLkW3xEbDzKJlwzpTpZlDORSG1OdS7gMw2MWnhvFtlI2UZQu5yY7SEFFxUVedmN60YYl0W0VlIkqch43PKdpko+A1QUrBjW8kTaIXxVSQofY89o5EEohBOYN/R+sz2hx9XQqCVU/bT6Su2UgzluX+LrhE6NsVX6dkQ0morahffIF7/p0EcdQ2qjcVzcDo0Sts9q5jJa4ROs/E8=

# Caching phrase.
cache:
  directories:
  - node_modules

# Dependency installation phrase.
install:
- npm install

# Build phrase
script:
- npm run build

# Custom deployment phrase.
after_success:
- node deployment\\bitballoon.js --site-id=$BB_SITE_ID --client-id=$BB_CLIENT_ID --client-secret=$BB_CLIENT_SECRET
